In [1]:
source("cachematrix.R")

In [2]:
#Calculating the inverse of a normal matrix
matriz1 <- matrix(c(1,2,3,4), nrow=2)
matriz1
solve(matriz1)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [3]:
#Creating a cacheMatrix
cmatriz1 <- makeCacheMatrix(matriz1)

writeLines('Matrix:')
cmatriz1$get()
writeLines("Inverse:")
cmatriz1$getinverse()

writeLines("\nCalling cacheSolve for the first time:")
cacheSolve(cmatriz1)

writeLines("\nCalling cacheSolve for the second time:")
cacheSolve(cmatriz1)

#New values
cmatriz1$set(matrix(c(10,20,30,40),nrow=2))
writeLines('\n\nNEW SET OF VALUES\nMatrix:')
cmatriz1$get()
writeLines("Inverse:")
cmatriz1$getinverse()

writeLines("\nCalling cacheSolve for the first time:")
cacheSolve(cmatriz1)

writeLines("\nCalling cacheSolve for the second time:")
cacheSolve(cmatriz1)

Matrix:


[,1] [,2]
[1,] 1    3   
[2,] 2    4

Inverse:


NULL


Calling cacheSolve for the first time:


Calculating the inverse


[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5


Calling cacheSolve for the second time:


[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5



NEW SET OF VALUES
Matrix:


[,1] [,2]
[1,] 10   30  
[2,] 20   40

Inverse:


NULL


Calling cacheSolve for the first time:


Calculating the inverse


[,1] [,2] 
[1,] -0.2  0.15
[2,]  0.1 -0.05


Calling cacheSolve for the second time:


[,1] [,2] 
[1,] -0.2  0.15
[2,]  0.1 -0.05